pages:
  -
    urls:
      - https://www.the-shop.com/1
      - https://www.the-shop.com/2
    element: button
      identifier:
        id: addToCartButton
        disabled: true


telegram:
  token: 123
  chats:
  - 1
  - 2
  - 3